apiVersion: v1
data:
  OLLAMA_URL: "http://ollama.ollama.svc.cluster.local"
  OLLAMA_PORT: "11434"
  OLLAMA_MODEL: "granite4:3b"
  DATABASE_URL: "meetup-mysql"
  DATABASE_PORT: "3306"
  OLLAMA_TIMEOUT: "180" # 3 min
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: scraper-cfm
